[build]
  command = "npm run build"
  publish = "dist"

# This redirect ensures that React Router works perfectly on Netlify!
# Without this, refreshing a page other than the home page will give a 404 error.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
