@echo off
echo Starting HireIQ FastAPI Backend Server (Port 8000)...
start cmd /k "set PYTHONPATH=%cd%\..&& uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
echo Starting HireIQ Streamlit Workspace (Port 8501)...
set PYTHONPATH=%cd%\..&& streamlit run app.py --server.port 8501
